// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmXt9PSR3ParX89E6A3r-y-jA4rV92In8',
    appId: '1:323239787668:web:89c6fca42df0999658c881',
    messagingSenderId: '323239787668',
    projectId: 'authentication-fd4f2',
    authDomain: 'authentication-fd4f2.firebaseapp.com',
    storageBucket: 'authentication-fd4f2.appspot.com',
    measurementId: 'G-LJHHZ77R6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rBlM52EMFdlBtYm67X-punTNQUr43wU',
    appId: '1:323239787668:android:4e00a9747d2fa16658c881',
    messagingSenderId: '323239787668',
    projectId: 'authentication-fd4f2',
    storageBucket: 'authentication-fd4f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawOQK6mTqETRgh5gPQMWD_4ZTllv5Aqs',
    appId: '1:323239787668:ios:158be879855c85e558c881',
    messagingSenderId: '323239787668',
    projectId: 'authentication-fd4f2',
    storageBucket: 'authentication-fd4f2.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCawOQK6mTqETRgh5gPQMWD_4ZTllv5Aqs',
    appId: '1:323239787668:ios:158be879855c85e558c881',
    messagingSenderId: '323239787668',
    projectId: 'authentication-fd4f2',
    storageBucket: 'authentication-fd4f2.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmXt9PSR3ParX89E6A3r-y-jA4rV92In8',
    appId: '1:323239787668:web:7b6ed4aa960e287558c881',
    messagingSenderId: '323239787668',
    projectId: 'authentication-fd4f2',
    authDomain: 'authentication-fd4f2.firebaseapp.com',
    storageBucket: 'authentication-fd4f2.appspot.com',
    measurementId: 'G-K93K6ZQ72R',
  );
}
